/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CiscoRouteImport } from './routes/cisco'
import { Route as ExchangeRouteImport } from './routes/exchange'
import { Route as FirewallRouteImport } from './routes/firewall'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as SearchRouteImport } from './routes/search'
import { Route as InventoryIdRouteImport } from './routes/inventory.$id'
import { Route as LoginRouteImport } from './routes/login'
import { Route as UsersRouteImport } from './routes/users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CiscoRoute = CiscoRouteImport.update({
  id: '/cisco',
  path: '/cisco',
  getParentRoute: () => rootRouteImport,
} as any)
const ExchangeRoute = ExchangeRouteImport.update({
  id: '/exchange',
  path: '/exchange',
  getParentRoute: () => rootRouteImport,
} as any)
const FirewallRoute = FirewallRouteImport.update({
  id: '/firewall',
  path: '/firewall',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIdRoute = InventoryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => InventoryRoute,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cisco': typeof CiscoRoute
  '/exchange': typeof ExchangeRoute
  '/firewall': typeof FirewallRoute
  '/inventory': typeof InventoryRouteWithChildren
  '/search': typeof SearchRoute
  '/inventory/$id': typeof InventoryIdRoute
  '/login': typeof LoginRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cisco': typeof CiscoRoute
  '/exchange': typeof ExchangeRoute
  '/firewall': typeof FirewallRoute
  '/inventory': typeof InventoryRouteWithChildren
  '/search': typeof SearchRoute
  '/inventory/$id': typeof InventoryIdRoute
  '/login': typeof LoginRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cisco': typeof CiscoRoute
  '/exchange': typeof ExchangeRoute
  '/firewall': typeof FirewallRoute
  '/inventory': typeof InventoryRouteWithChildren
  '/search': typeof SearchRoute
  '/inventory/$id': typeof InventoryIdRoute
  '/login': typeof LoginRoute
  '/users': typeof UsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cisco'
    | '/exchange'
    | '/firewall'
    | '/inventory'
    | '/search'
    | '/inventory/$id'
    | '/login'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cisco'
    | '/exchange'
    | '/firewall'
    | '/inventory'
    | '/search'
    | '/inventory/$id'
    | '/login'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/cisco'
    | '/exchange'
    | '/firewall'
    | '/inventory'
    | '/search'
    | '/inventory/$id'
    | '/login'
    | '/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CiscoRoute: typeof CiscoRoute
  ExchangeRoute: typeof ExchangeRoute
  FirewallRoute: typeof FirewallRoute
  InventoryRoute: typeof InventoryRouteWithChildren
  SearchRoute: typeof SearchRoute
  LoginRoute: typeof LoginRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cisco': {
      id: '/cisco'
      path: '/cisco'
      fullPath: '/cisco'
      preLoaderRoute: typeof CiscoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exchange': {
      id: '/exchange'
      path: '/exchange'
      fullPath: '/exchange'
      preLoaderRoute: typeof ExchangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/firewall': {
      id: '/firewall'
      path: '/firewall'
      fullPath: '/firewall'
      preLoaderRoute: typeof FirewallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/$id': {
      id: '/inventory/$id'
      path: '/$id'
      fullPath: '/inventory/$id'
      preLoaderRoute: typeof InventoryIdRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface InventoryRouteChildren {
  InventoryIdRoute: typeof InventoryIdRoute
}

const InventoryRouteChildren: InventoryRouteChildren = {
  InventoryIdRoute: InventoryIdRoute,
}

const InventoryRouteWithChildren = InventoryRoute._addFileChildren(
  InventoryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CiscoRoute: CiscoRoute,
  ExchangeRoute: ExchangeRoute,
  FirewallRoute: FirewallRoute,
  InventoryRoute: InventoryRouteWithChildren,
  SearchRoute: SearchRoute,
  LoginRoute: LoginRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
